# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userfav',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userfocus',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userleavingmessage',
            old_name='add_time',
            new_name='create_time',
        ),
    ]
