# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20171224_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(db_table='article_tag', related_name='tag_article', to='blogger.Tag', verbose_name='标签'),
        ),
    ]
