# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='focus',
            field=models.IntegerField(default=0, verbose_name='关注人数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refocus',
            field=models.IntegerField(default=0, verbose_name='被关注人数'),
        ),
    ]
